<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Model\PostmanTrackingInterface;

/**
 * PostmanTrackingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostmanTrackingRepository extends \Doctrine\ORM\EntityRepository
{
	public function save(PostmanTrackingInterface $postmanTracking) {
		$em = $this->getEntityManager();
		$em->persist($postmanTracking);
		$em->flush();
	}
}
