app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_Postman:
    type: rest
    prefix: /v1
    resource: 'AppBundle\Controller\PostmanController'
    name_prefix: api_1_ #naming collision

app_PostmanTracking:
    type: rest
    prefix: /v2
    resource: 'AppBundle\Controller\PostmanTrackingController'
    name_prefix: api_2_ #naming collision